[project]
name = "melora-backend"
version = "0.1.0"
description = "A modular FastAPI backend for searching, streaming, and downloading music from YouTube."
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Melora Developer" }
]
dependencies = [
    "fastapi==0.135.1",
    "uvicorn==0.41.0",
    "yt-dlp==2026.3.3",
    "pydantic==2.12.5",
    "sqlalchemy==2.0.48",
    "pydantic-settings==2.13.1",
    "python-dotenv==1.2.2",
]

[project.optional-dependencies]
dev = [
    "ruff==0.15.6",
]

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "UP", # pyupgrade
]
ignore = ["B008"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
