"""add listening history

Revision ID: 008dd920c126
Revises: fa441c289bc6
Create Date: 2026-08-06 22:55:49.306113

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "008dd920c126"
down_revision: Union[str, None] = "fa441c289bc6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listening_history",
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("song_id", sa.String(), nullable=True),
        sa.Column("played_at", sa.DateTime(), nullable=False),
        sa.Column("play_duration", sa.Integer(), nullable=True),
        sa.Column("context_playlist_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["songs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("listening_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_listening_history_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_listening_history_song_id"), ["song_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_listening_history_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("listening_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_listening_history_user_id"))
        batch_op.drop_index(batch_op.f("ix_listening_history_song_id"))
        batch_op.drop_index(batch_op.f("ix_listening_history_id"))

    op.drop_table("listening_history")
    # ### end Alembic commands ###
