"""create_admin_settings_table

Revision ID: 9d024312997e
Revises: 736221beb6de
Create Date: 2026-07-28 23:33:29.519173

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d024312997e"
down_revision: str | None = "736221beb6de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_settings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_name", sa.String(), nullable=False),
        sa.Column("debug", sa.Boolean(), nullable=False),
        sa.Column("cache_enabled", sa.Boolean(), nullable=False),
        sa.Column("max_cache_size_gb", sa.Integer(), nullable=False),
        sa.Column("cache_ttl_hours", sa.Integer(), nullable=False),
        sa.Column("redis_stream_cache_ttl", sa.Integer(), nullable=False),
        sa.Column("jwt_access_token_expire_minutes", sa.Integer(), nullable=False),
        sa.Column("jwt_refresh_token_expire_days", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("admin_settings")
    # ### end Alembic commands ###
