"""add user stats

Revision ID: a43add9ed4ae
Revises: 008dd920c126
Create Date: 2026-08-06 22:58:41.003807

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a43add9ed4ae"
down_revision: Union[str, None] = "008dd920c126"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_stats",
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("total_plays", sa.Integer(), nullable=False),
        sa.Column("total_play_time", sa.Integer(), nullable=False),
        sa.Column("top_songs", sa.JSON(), nullable=False),
        sa.Column("top_artists", sa.JSON(), nullable=False),
        sa.Column("genres", sa.JSON(), nullable=False),
        sa.Column("plays_last_30_days", sa.JSON(), nullable=False),
        sa.Column("last_calculated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_user_stats_user_id"),
    )
    with op.batch_alter_table("user_stats", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_stats_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_user_stats_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_stats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_stats_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_stats_id"))

    op.drop_table("user_stats")
    # ### end Alembic commands ###
