"""add playlist share tokens

Revision ID: ac90e01ee83f
Revises: 9d024312997e
Create Date: 2026-08-05 23:28:20.702922

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac90e01ee83f"
down_revision: str | None = "9d024312997e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlist_shares",
        sa.Column("playlist_id", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("playlist_shares", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_playlist_shares_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_playlist_shares_playlist_id"), ["playlist_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_playlist_shares_token"), ["token"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("playlist_shares", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_playlist_shares_token"))
        batch_op.drop_index(batch_op.f("ix_playlist_shares_playlist_id"))
        batch_op.drop_index(batch_op.f("ix_playlist_shares_id"))

    op.drop_table("playlist_shares")
    # ### end Alembic commands ###
