"""add artists

Revision ID: fa441c289bc6
Revises: 8bfb8ac8a75b
Create Date: 2026-08-06 22:38:00.291059

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa441c289bc6"
down_revision: Union[str, None] = "8bfb8ac8a75b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("thumbnail_url", sa.String(), nullable=True),
        sa.Column("bio", sa.String(), nullable=True),
        sa.Column("genres", sa.JSON(), nullable=False),
        sa.Column("external_ids", sa.JSON(), nullable=False),
        sa.Column("monthly_listeners", sa.Integer(), nullable=True),
        sa.Column("follower_count", sa.Integer(), nullable=False),
        sa.Column("enriched_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("artists", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_artists_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_artists_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_artists_slug"), ["slug"], unique=True)

    op.create_table(
        "song_artist",
        sa.Column("song_id", sa.String(), nullable=False),
        sa.Column("artist_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["songs.id"],
        ),
        sa.PrimaryKeyConstraint("song_id", "artist_id"),
    )
    op.create_table(
        "user_artist_follows",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("artist_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "artist_id"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_artist_follows")
    op.drop_table("song_artist")
    with op.batch_alter_table("artists", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artists_slug"))
        batch_op.drop_index(batch_op.f("ix_artists_name"))
        batch_op.drop_index(batch_op.f("ix_artists_id"))

    op.drop_table("artists")
    # ### end Alembic commands ###
