export const API_LIMITS = {
    RELATED_SONGS: 6,
    ARTIST_RECENTLY_PLAYED: 10,
    ARTIST_SUGGESTED_PAGE: 20,
    YOUTUBE_SEARCH: 8,
    DISCOVER_PLAYLISTS: 50,
    RECENT_HISTORY: 50,
    RECOMMENDATIONS: 20,
    RADIO_COUNT: 25,
} as const
