name: Deploy Melora

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploying to the Server
    runs-on: ubuntu-latest

    # Required for OIDC token exchange with GitHub
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_CLIENT_ID }}
          audience: ${{ secrets.TS_AUDIENCE }}
          tags: tag:ci

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 \
            -o StrictHostKeyChecking=no \
            ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} \
            "cd ${{ secrets.PROJECT_ROOT }} && bash deploy.sh"